server:
  port: 8087
spring:
  application:
    name: histories
  datasource:
    url: jdbc:mysql://mysql-histories:3306/histories_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
