server:
  port: 8761

spring:
  application:
    name: eureka-server
  # Menonaktifkan pendaftaran service otomatis
  cloud:
    service-registry:
      auto-registration:
        enabled: false

eureka:
  client:
    # 1. WAJIB: Mencegah Eureka Server mendaftarkan dirinya sebagai klien.
    register-with-eureka: false 
    # 2. WAJIB: Mencegah Eureka Server mencoba mencari daftar layanan lain.
    fetch-registry: false 
    # 3. Definisikan URL server itu sendiri (untuk tampilan dashboard)
    service-url:
      defaultZone: http://eureka-server:8761/eureka