# File: eureka-server/src/main/resources/application.properties

server.port=8761
spring.application.name=eureka-server

# 1. WAJIB: Mencegah Eureka Server mendaftarkan dirinya sebagai klien.
eureka.client.register-with-eureka=false 

# 2. WAJIB: Mencegah Eureka Server mencoba mencari daftar layanan lain (registry).
eureka.client.fetch-registry=false 

# 3. WAJIB: Definisikan URL/Hostname-nya sendiri.
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka