server:
  port: 8083

spring:
  application:
    name: transactions

  datasource:
    url: jdbc:mysql://mysql:3306/transactions_db
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

reloadly:
  client-id: ${RELOADLY_CLIENT_ID}
  client-secret: ${RELOADLY_CLIENT_SECRET}
  auth-url: ${RELOADLY_AUTH_URL}
  topups-url: ${RELOADLY_TOPUPS_URL}

users:
  service:
    url: http://localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
